version: '2'
networks:
  myshop:
    driver: overlay
services:
  proxy:
    image: linuxpreview-on.azurecr.io/proxy:1.0
    ports: ["80:80"]
    networks:
      - myshop
  products:
    image: linuxpreview-on.azurecr.io/products-api:99
    networks:
      - myshop
  ratings:
    image: linuxpreview-on.azurecr.io/ratings-api:99
    networks:
      - myshop
  recommandations:
    image: linuxpreview-on.azurecr.io/recommandations-api:99
    networks:
      - myshop
  shop:
    image: linuxpreview-on.azurecr.io/shop-front:99
    networks:
      - myshop
    environment:
      - SHOP_PRODUCTS_API_URL=/products/
      - SHOP_RATINGS_API_URL=/ratings/
      - SHOP_RECOMMANDATIONS_API_URL=/recommandations/