version: '3.1'
networks:
  myshop:
    driver: overlay
services:
  proxy:
    build:
      context: ./Proxy
      dockerfile: Dockerfile 
    image: shop-proxy
    ports: ["8080:80"]
    networks:
      - myshop
    deploy:
      mode: replicated
      replicas: 1
  products:
    build:
      context: ./ProductsApi
      dockerfile: Dockerfile
    image: products-api
    networks:
      - myshop
    deploy:
      mode: replicated
      replicas: 1
  ratings:
    build:
      context: ./RatingsApi
      dockerfile: Dockerfile
    image: ratings-api
    networks:
      - myshop
    deploy:
      mode: replicated
      replicas: 1
  recommandations:
    build:
      context: ./RecommandationsApi
      dockerfile: Dockerfile
    image: recommandations-api
    networks:
      - myshop
    deploy:
      mode: replicated
      replicas: 3
      resources:
          limits:
            cpus: '0.25'
            memory: 512M
          reservations:
            cpus: '0.001'
            memory: 20M
  shop:
    build:
      context: ./ShopFront
      dockerfile: Dockerfile
    image: shop-front
    networks:
      - myshop
    environment:
      - SHOP_PRODUCTS_API_URL=products
      - SHOP_RATINGS_API_URL=ratings
      - SHOP_RECOMMANDATIONS_API_URL=recommandations
    deploy:
      mode: replicated
      replicas: 1